### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by tsamardzic** [reldi-data/SETimes.SRPlus#2]
Currently a copy of hr500k, does not correspond to the content.

**Comment by nljubesi** [comment]
All four dataset READMEs are to change. The hr500k README is also obsolete as it is an old version of the current reldi-data repo README.

The dataset-specific READMEs are to 1. describe the dataset and 2. report on the current state of validation. I suggest we deal with all four READMEs in one go.

**Comment by tsamardzic** [comment]
I think we should separate data description from reports. Moving the discussion to the reldi-data/reldi-data issue #6.
